---
title: "ETC5521 Assignment 1"
subtitle: "Board Games analysis"
team: brolga
author:
  - [Dhruv Nirmal]
  - [Gui Gao]
date: "`r Sys.Date()`"
output: 
  html_document
---

[This assignment is for ETC5521 Assignment 1 by Team `r rmarkdown::metadata$team` comprising of `r knitr::combine_words(rmarkdown::metadata$author)`.]{style="color:#006DAE;"}


# Introduction and motivation

## Introduction:

The classic Board Games have been around for decades, bringing people together to enjoy the traditional game. In Greece there are many popular board game associations and 'fan clubs' which organise many tournaments and offer a wealth of prizes. 

Today, although Computer Games are in a golden age of development with technological support, there are still many great board games that are released each year and attract a lot of attention.

**Board Game Geek** is a specialist board game website. Users can find every board game and information about it. This information includes descriptions of the games, reviews, user ratings, professional ratings, prices, where to buy and more.


## Motivation:

My teammates and I are both interested in board games and have tried many interesting board games. This study and analysis of the huge dataset of board games can help us understand board games from a different perspective, and also help us understand the whole landscape of board games and how it has changed over time.

So, we have tried to dig deeper into the data itself to show some reports and interesting data visualisations of the results.


# Data description


# Questions of interest

## Questions list

* a.

Q1.
How board game ratings change by year of publication?

Q2.
Trends in game mechanics over time.

Q3.
Trends in board game publication rates over time.

Q4.
What are the common game mechanics and their changes in prevalent?

Q5.
What types of games are becoming increasingly popular?

Q6.
How many games have each listed how many mechanics?

Q7.
What is the distribution of ratings for the games?

Q8.
Is there a linear relationship between the year of release of a game and the average rating it receives?

Q9.
Are Board Game Descriptions more positive or negative?

Q10.
What are the 10 most common words used in board game descriptions?

## Interested Questions

* a.

Q1.
What are the common game mechanics and their changes in prevalent?

Q2.
What is the distribution of ratings for the games?


# Expected findings

* a.
Q1.
The most common game mechanics maybe the 'Acting', 'Dice Rolling' and 'Hand Management'. I guess the more common the game mechanics are, the more popular they will become.

Q2.
I guess the ratings for the games follow a normal distribution.


# Analysis and findings

[FILL] Should include at least one plot or numerical summary for each of your questions, that helps the reader arrive at an answer. You should also write paragraphs describing the methods, summaries and findings. 

# References
